{{/*
#
# Copyright (c) 2019 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{ if ne .Values.namespace "default" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
{{ end }}
