#
# Copyright (c) 2019 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# Default values for node-feature-discovery.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# namespace to use for chart resources.  Must be specified.
namespace: default

# label for the daemonset to find its pods
app_label: node-feature-discovery

# docker image to use for the pods
image: quay.io/kubernetes_incubator/node-feature-discovery:v0.3.0

# interval (in secs) to scan the node features
scan_interval: 60

# key/value pair to match against node labels to select which nodes
# should run the node feature discovery.  Defaults to all nodes.
node_selector_key:
node_selector_value:
